name: flutter_barcode_scanner
description: A plugin for barcode scanning support on Android and iOS. Supports barcodes, QR codes, etc.
version: 2.0.0
homepage: https://github.com/AmolGangadhare/flutter_barcode_scanner

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.22
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.25.2

flutter:
  plugin:
    platforms:
      android:
        package: com.amolg.flutterbarcodescanner
        pluginClass: FlutterBarcodeScannerPlugin
      ios:
        pluginClass: SwiftFlutterBarcodeScannerPlugin

  assets:
    - assets/icons/flashOff.svg
    - assets/icons/flashOn.svg
    - assets/icons/cancel-button.svg
    - assets/icons/camera-switch.svg
